### ISSUE TITLE
Support for other coordinate systems?

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/pyradiosky#119]
`SkyModel` currently assumes that HEALPix maps are ICRS frame whenever `hpx_inds` are given but ra/dec are not. Since the GSM is usually produced in galactic coordinates, it might behoove us to support source catalogs/maps in other coordinate systems.

Along this line, it might be make sense to use a `SkyCoord` instance for our position data so that transformations are easier. If we're feeling really ambitious, `SkyModel` could even be made a subclass of `SkyCoord`, giving us the frame, ra, dec, l, b, az, alt, etc. attributes directly.

**Comment by bhazelton** [comment]
In a discussion on our telecon about this we thought maybe we should just add a `frame` attribute to the object (which will be round-tripped through files) and a method for transforming frames using `SkyCoord`

**Comment by mkolopanis** [comment]
Could also be that we could turn the ra/dec arrays into a skycoord object

**Comment by mkolopanis** [comment]
oh this was literally adam's suggestion too. I'm behind the times huh?

**Comment by mkolopanis** [comment]
regarding the skyframe idea, we could easily pipe through some of the attributes like ra/dec/etc that adam mentioned as parameters on the skymodel object. This way there is no loss of api too. but then I'm not sure if we can have the value of a UVParameter be a property itself? That sounds like untested waters. Might need to stray away from UVParameters or get really smart?

**Comment by aelanman** [comment]
@jpober I should be able to make it to that one. Sorry I couldn't make today's!

**Comment by jpober** [comment]
It seems like we could have a general set of (lat, lon) coords on a SkyModel object.  The astropy frame.get_representation_component_names can be used to provide a mapping of what (lat, lon) means for a particular frame.  We could then just have a generic transformation method.  We could also have the names of (lat, lon) defined given the frame, and then have the SkyModel object return the lat value if you're in 'galactic' frame and ask for b.

**Comment by mkolopanis** [comment]
We discussed further today about whether or not to move to keeping a skycoord object attached as a "coord" attribute. This could require a large API change though and may be better suited for a later date? We could also make properties for common lon/lat pairs like ra/dec which would return the values of the skycoord object if it is in a frame which supports them.

**Comment by aelanman** [comment]
As I understand it, we want to make the following changes:

1. Make a required UVParameter which carries a SkyCoord. This will handle the coordinates and frame information. Possibly also time and observatory location?
2. Make properties for `ra`, `dec`, `gl`, `gb` which access the corresponding SkyCoord attributes or error if in the wrong frame.
3. Update file read/write methods to accept frame information.
4. Write a transform function which will call `SkyCoord.transform_to`.

Instead of making separate properties which all do the same thing, we could also try writing a `__getattribute__` function to handle the different coordinate names.

In the future -- support pixel coordinates: https://docs.astropy.org/en/stable/wcs/index.html

**Comment by bhazelton** [comment]
I'd actually lean towards making API level changes sooner rather than later if we want to do them. We still don't have a huge user community but it is growing, so making changes earlier is less likely to cause pain. We'd still need a deprecation period though, since we do have some users.
