### ISSUE TITLE
Large memory overhead for skymodels

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyradiosky#127]
This may not be a "fixable" issue, but wanted to get tracking this. 
For a 768 frequency, nside 512 healpix map, a skymodel object can take over 300GB of ram. Compared to the ~30-50GB of the actual input map, the overhead is quite large. Now we will get a factor of 4 overhead just from instantiating the Stokes array but maybe there are other places we are duplicating data that doesn't need it? Or maybe there's nothing better we can do. 

is it possible to use sparse arrays (this would get complicated with our 3-D array and I don't think we can use quantities anymore)?
maybe other slick/smart solutions?

**Comment by aelanman** [comment]
In addition to inflating Stokes-I to a full stokes array, the skymodel `__init__` computes `coherency_radec` which has shape `(2, 2, Nfreqs, Ncomponents)`.

One way to avoid that overhead would be to replace the stokes array with separate `stokes_I`, `stokes_Q` etc. attributes, and only fill Q, U, V with nonzero values. We have an index of which sources are polarized, so it would be relatively straightforward to only keep QUV for polarized sources and.

The overhead from `coherency_radec` can be avoided by having it be generated separately from the init, so it's only made by request. If we were working in a functional programming language, we could define it that way and avoid having to store it altogether.

**Comment by aelanman** [comment]
I assume that caches it to disk?

With or without it, we'll still need the full `coherency_radec` in memory for simulations. Avoiding up-front computation would save on memory for other uses of `pyradiosky`.

**Comment by mkolopanis** [comment]
I'm not sure specifically where it is cached. But could look to see what it
does.

**Comment by mkolopanis** [comment]
also looks like it is stored in memory. All cached property really does is let you lazily evaluate a function later then let it get saved to memory as a new attribute. You can also delete the cache or set a time to live (ttl). this is what it looks like at least based on looking through the code briefly. I know @steven-murray has used it before maybe he has more insight.

**Comment by aelanman** [comment]
For the sake of this issue, I think taking the calculation of `coherency_radec` from __init__ is the answer. Then, the only quantities kept in memory after reading a catalog file are the data products in the file. For simulation, though, we'll still have to deal with the memory overhead.

The issue with the calculation of `coherency_radec` isn't that it takes a lot of time (which caching would address) but that it uses more memory. By my count, SkyModel loads the following `Ncomponents`-sized datasets from file (assuming spectral type = full):
- `stokes = (4, Ncomponents, Nfreqs)`
- `ra = (Ncomponents,)`
- `dec = (Ncomponents,)`
- `hpx_ind = (Ncomponents,)`

and generates the following: 
- `coherency_radec =  (2,2, Nfreqs, Ncomponents)`  on init
- `local_coherency_matrix = (2,2,Nfreqs, O(Ncomponents/2))`  whenever requested by simulation. (Only sources above horizon)
- `pos_lmn = (3, Ncomponents)`, when `update_positions` is run
- `above_horizon = (Ncomponents,)` type bool,  when `update_positions` is run
- `alt_az = (2, Ncomponents)`,  when `update_positions` is run
- `coherency_rotation_matrix (2,2, Npol_above_horizon)`, whenever `coherency_calc` is run. Npol_above_horizon is the number of polarized sources above the horizon.
- `_polarized = (N_pol)`, on init, indices of sources with nonzero Q, U, and/or V.

The real memory hogs are the coherency matrices, especially when dealing with a full-frequency sky model. If all you're doing is reading in a catalog and writing it back out, then it shouldn't be necessary to deal with them, so we can consider removing the generation of `coherency_radec` from the init. However, these are necessary for simulation, so we'll still be memory limited with pyuvsim.

Now, pyuyvsim already takes into account the memory overhead of SkyModel and divides the component list to stay within available memory. As usual, we're facing a tradeoff between speed and memory.

There may be a way to redesign pyuvsim's calculation to avoid precomputing the coherencies while maintaining speed. The advantage to precomputing here is that we can leverage numpy threading speed while keeping the steps separate. Instead, we could write a cython extension to do the visibility calculation given topocentric source positions, E-field beam values, and stokes parameters, letting it do coherency calc (and rotation for polarized sources) internally. With that, we'd get the speed of numpy compiled code while avoiding the need to cache intermediate data products like `coherency_radec`, `local_coherency`, or rotation matrices.

**Comment by bhazelton** [comment]
I think it's fine to take the coherency calculation out of init and only call it as needed. There are many use cases for SkyModel that do not need the coherencies.
