### ISSUE TITLE
Add beam value support

### ISSUE THREAD

**Issue by rlbyrne** [RadioAstronomySoftwareGroup/pyradiosky#13]
FHD deconvolution outputs beam amplitude values at source locations. These should be documented in SkyModel objects.

**Comment by aelanman** [comment]
Is this to provide meaning to units like Jy/beam?

**Comment by rlbyrne** [comment]
No, this is to show the instrument sensitivity at the source location. It is a proxy for the reliability of the deconvolution result.

**Comment by bhazelton** [comment]
I think this was implemented in PR #9, is that correct @rlbyrne?

**Comment by rlbyrne** [comment]
Yes, that's correct. I'll go ahead and close.
