### ISSUE TITLE
Some init keywords are ignored

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyradiosky#131]
when initializing a healpix map, some keywords seem to be entirely ignored with no warning or information for the user. This particular case is for ra/dec, which in the context of #119 means that healpix maps in other coordinate systems always have the wrong ra/dec even if the user tries to set them with init.

https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/d990f80642b1e9117bbd3e2245c1e1821fc4d641/pyradiosky/skymodel.py#L480-L482

**Comment by bhazelton** [comment]
We decided to allow users to override the ra/dec in the init, but we need a warning to users that doing that means that the ra/dec doesn't match the pixel inds.

**Comment by bhazelton** [comment]
we also need to test that this is consistent through the `healpix_to_point` and `point_to_healpix` loop.
