### ISSUE TITLE
use TETE frame?

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyradiosky#141]
I think this is a question I don't really understand, but now in astropy>4.2 they have introduced the [TETE frame](https://docs.astropy.org/en/stable/api/astropy.coordinates.TETE.html). Is it better to transform to that frame then calculate the altaz of each source. This frame claims to account for precession and nutation, it would obviously require a stricter astropy requirement. 

https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/602cae56e4c24e5aa03948983f469d869a166015/pyradiosky/skymodel.py#L1198

**Comment by bhazelton** [comment]
I think we really need AltAz for the coherency calculation because that calculation is used to get the coherency in the same frame as the beam, which is in AltAz in e.g. pyuvsim.
