### ISSUE TITLE
Error message with SkyModel input lengths

### ISSUE THREAD

**Issue by kelceydavis33** [RadioAstronomySoftwareGroup/pyradiosky#142]
When a SkyModel is passed multiple inputs and one is of different length, the error message reads:

`ValueError: UVParameter <pyuvdata.parameter.UVParameter object at 0x7fe0a97efe80> is not expected shape. Parameter shape is (699,), expected shape is (26734,).`

This could be more intuitive to solve if the error indicated which input is of an incorrect length.

**Comment by mkolopanis** [comment]
Starting at `pyuvdata` version 2.1.5 this error message should print out the name of the parameter instead of the memory address. Can you check on your `pyuvdata` version please?

**Comment by kelceydavis33** [comment]
I see that I am running 2.1.3. Sorry for the confusion! I will update.

**Comment by bhazelton** [comment]
We could also check the input shapes in the init rather than leaving it to the check function to catch. Then we could have a much more useful error message.

**Comment by mkolopanis** [comment]
This is also a good option!

**Comment by kelceydavis33** [comment]
I have tested all inputs to the SkyModel to ensure that they have correct error messages with the 2.1.5 version. All seem to work correctly, but changing the name and stokes parameter to an incorrect length both produce the identical error message:

`ValueError: UVParameter coherency_radec is not expected shape. Parameter shape is (2, 2, 1, 3), expected shape is (2, 2, 1, 2).`
