### ISSUE TITLE
Init from Skycoord object

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyradiosky#143]
Came up on the call 04 May 2021, should we be able to initialize from or require initialization from a skycoord object?
This could abstract away our need to init from ra/dec/frame etc, and allow inputs in lat/lon or arbitrary frames.

Having the component positions held in a skycoord object (which is a working theory for #119) would allow some more flexibility with initialization if just given a skycoord object. This would be a major api change though, and I can still see usefulness in giving just a list of ra/dec/flux for sources.

**Comment by bhazelton** [comment]
Done in #186
