### ISSUE TITLE
skyh5 reader generates warning about input ra/decs being used rather than healpix coordinates

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyradiosky#150]
It's not ideal to be generating warnings every time we read in Healpix objects.

**Comment by mkolopanis** [comment]
yeah these warnings came from a PR I made thinking about users providing input ra/dec into objects. I didn't consider that read it passes all the parameters through init to set up the object (opposed to how uvh5 works in pyuvdata where it sets all the parameters explicitly as the file is read).

**Comment by bhazelton** [comment]
We decided in the telecon on 7/27/21 to make ra/dec be optional parameters for healpix maps. They will not be set in the `__init__` method for healpix maps, instead we will move that functionality to a method (which will be called in `healpix_to_point`). This might break some things, need to think about that.
