### ISSUE TITLE
Coherency rotations for non terrestrial observatories

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyradiosky#188]
It seems pretty likely we're not doing rotations of the polarized coherency matrix to the local frame correctly when using MoonLocations (instead of EarthLocations).  `_calc_coherency_rotation` calls `_calc_rotation_matrix` which in turns calls `_calc_average_rotation_matrix` which itself creates a SkyCoord to go to alt/az.

@aelanman says: Fixing it might not be too complicated, though. It would require changing a line in _calc_average_rotation_matrix to transform to either altaz or lunartopo, depending on whether self.telescope_location is an EarthLocation or a MoonLocation.

**Comment by bhazelton** [comment]
I started trying to fix this in #198. It hasn't been adequately tested yet, so unclear if issues remain.

**Comment by bhazelton** [comment]
I think that #198, in combination with updates and tests in pyuvsim and pyuvdata, has done this.
