### ISSUE TITLE
Use pre-commit hooks

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyradiosky#19]
Pre-commit hooks reduce commits that just change a lot of formatting. We can enforce black and flake8 compliance there. We can also use it directly in tests for linting, so there's no duplication.

**Comment by bhazelton** [comment]
@steven-murray was this fixed by the PR I just merged?

**Comment by bhazelton** [comment]
@steven-murray was this fixed by the PR I just merged?

**Comment by steven-murray** [comment]
Yup. Closed by #40.
