### ISSUE TITLE
make_flat_spectrum_eor requires a specific frame

### ISSUE THREAD

**Issue by danielquinter-brown** [RadioAstronomySoftwareGroup/pyradiosky#210]
Currently, attempting to run make_flat_spectrum_eor.py as a script fails with 
`ValueError: If initializing with values, all of ['nside', 'frame', 'hpx_inds', 'stokes', 'spectral_type', 'freq_array'] must be set. Received: ['nside', 'hpx_inds', 'stokes', 'spectral_type', 'freq_array']` 
The script does not set a frame or accept a frame argument to be passed, which SkyModel requires, so an error is thrown when trying to return a SkyModel.

**Comment by jpober** [comment]
@danielquinter-brown Do you think you can make a PR with your fix for this issue?  Happy to sit down and show you how to do it if you're unsure.

**Comment by bhazelton** [comment]
fixed in #216
