### ISSUE TITLE
Description of SkyModel

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyradiosky#22]
It might be useful to clearly describe, either in the `skymodel` module docstring, or the `SkyModel` class docstring, that the `SkyModel` class is able to handle diffuse skies by considering each pixel as a point source.

**Comment by bhazelton** [comment]
This is no longer quite accurate. In fact, SkyModel represents healpix maps differently than point sources, allowing downstream codes to handle them as they like. There is a new `component_type` parameter that can be set to `'healpix'` or `'point'` to identify what the components on the object are. There are some improvements in the works to clarify that the HEALPix components are assumed to be sky brightnesses (so in units like Kelvin or Jy/str) while point-like components are assumed to be flux densities (so in units like Jy). We will also add a method to convert 'healpix' components to 'point' components by multiplying by the pixel area.
