### ISSUE TITLE
Concatenation fails

### ISSUE THREAD

**Issue by rlbyrne** [RadioAstronomySoftwareGroup/pyradiosky#245]
Running `concat` returns this astropy error:
```
  File "/Users/ruby/opt/anaconda3/envs/py310/lib/python3.10/site-packages/pyradiosky/skymodel.py", line 2809, in concat
    this.skycoord = sc_concatenate((this.skycoord, other.skycoord))
  File "/Users/ruby/opt/anaconda3/envs/py310/lib/python3.10/site-packages/astropy/coordinates/funcs.py", line 387, in concatenate
    concatenate_representations([c.data for c in coords]), frame=scs[0].frame
  File "/Users/ruby/opt/anaconda3/envs/py310/lib/python3.10/site-packages/astropy/coordinates/funcs.py", line 317, in concatenate_representations
    raise TypeError("Input representations must all have the same type.")
TypeError: Input representations must all have the same type.
```

**Comment by bhazelton** [comment]
This is actually an error that is being thrown by astropy. Representation types on skycoord objects are ‘spherical’, ‘cartesian’, or ‘cylindrical’ and I'm guessing from the error message that's what it's talking about. Can you give some context about the catalogs that you're trying to concatenate?

**Comment by rlbyrne** [comment]
Both catalogs I generated myself with the same script, so I'm surprised those representations could differ. I create the catalogs with this command:
```
catalog = pyradiosky.SkyModel(
      name=name,
      extended_model_group=extended_model_group,
      ra=Longitude(ra_deg, units.deg),
      dec=Latitude(dec_deg, units.deg),
      stokes=stokes,
      spectral_type="spectral_index",
      reference_frequency=Quantity(np.full(ncomps, target_freq_hz), "hertz"),
      spectral_index=spectral_indices_use,
      frame="icrs",
  )
 ```

**Comment by bhazelton** [comment]
weird. Can you inspect `catalog.skycoord.representation_type`? We're using astropy.coordinates.concatenate to concatenate the skycoords. Can you try concatenating just the skycoords (available at catalog.skycoord) using that function to see if you get the same error? Alternatively can you write up a minimal working example so I can play with this?

**Comment by rlbyrne** [comment]
I've identified that the problem only occurs when I try to perform a second concatenation on a catalog that has already been concatenated. `catalog.skycoord.representation_type` is `<class 'astropy.coordinates.representation.spherical.SphericalRepresentation'>` for both catalogs. @bhazelton, I will send you a somewhat simplified example script with data files.

**Comment by bhazelton** [comment]
Oh, but I may have just come up with a work around that we can use in pyradiosky. The following does not error:
```
import astropy.units as units
from astropy.coordinates import SkyCoord, concatenate

sc1 = SkyCoord(ra=350*units.deg, dec = 35*units.deg)
sc2 = SkyCoord(ra=351*units.deg, dec = 36*units.deg)
sc3 = SkyCoord(ra=352*units.deg, dec = 37*units.deg)

sc_12 = SkyCoord([sc1, sc2])

sc_123 = SkyCoord([sc_12, sc3])
```

**Comment by rlbyrne** [comment]
Thank you! This definitely does seem like an astropy bug. I created a workaround by just creating a new SkyModel object and concatenating the attributes independently, but your fix looks good too.

**Comment by bhazelton** [comment]
@rlbyrne I just pushed a branch called `fix_concat`. Can you see if it works for you?

**Comment by rlbyrne** [comment]
It worked! Thank you.
