### ISSUE TITLE
I dislike setting instance attributes outside of __init__

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyradiosky#25]
What is the motivation for having this method set instance attributes within the method?

https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/9f85fee27f92c34818298570b7bf85e8bd47fc24/pyradiosky/skymodel.py#L297

There are times when updating instance attributes is reasonable, but I almost always think its a bad idea. Can we get around it somehow?

**Comment by jpober** [comment]
This specific "update" method is probably OK but a good rule of thumb to keep in mind.  Some development is perhaps warranted to fix this.

**Comment by jpober** [comment]
This logic makes sense for this particular method, we'll keep an eye out for it in future cases.
