### ISSUE TITLE
Add instantiation/reading class methods?

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyradiosky#26]
I kind of like adding `@classmethod`s to classes like `SkyModel` that allow instantiating from different sources. Eg. one could add a `SkyModel.from_healpix(hmap, indices, freqs)` method. 

It's not necessarily a huge improvement over separate functions, except that (to me) it keeps everything a bit tidier, especially if there are going to be multiple ways to instantiate.

**Comment by bhazelton** [comment]
This was done in PR #91
