### ISSUE TITLE
make an analytic test for polarized coherency calculations

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyradiosky#3]

**Comment by jpober** [comment]
Turns out this is hard.  (Much) work in progress.

**Comment by bhazelton** [comment]
What we have is a test that verifies that using an analytic polarized beam (based on an analytic dipole), visibilities from polarized sources are smooth as the source moves through zenith. This is the test that took a long time to pass and convinced us things were working properly.

We also have a test where we saved out visibility data and check that we get the same numbers when we run again. This is mostly a regression test.

What we don't have is a test that analytically calculates the coherencies and checks that our coherencies match. We do have this check for unpolarized sources, so between those and the smooth visibility test we think we've covered this.
