### ISSUE TITLE
No docstrings in public methods

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyradiosky#33]
Here: https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/9f85fee27f92c34818298570b7bf85e8bd47fc24/pyradiosky/utils.py#L18

and here: https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/9f85fee27f92c34818298570b7bf85e8bd47fc24/pyradiosky/utils.py#L29

**Comment by bhazelton** [comment]
@steven-murray was this fixed by the PR I just merged?

**Comment by steven-murray** [comment]
Yes. Closed by #40 .
