### ISSUE TITLE
Add/concat function

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyradiosky#39]
To combine catalogs

**Comment by bhazelton** [comment]
On the June 1, 2020 telecon we decided that we will not combine catalogs with different spectral_type or different freq_array. Users can call the new at_frequencies method to make all catalogs full type at a list of frequencies and then they can be combined.

**Comment by jpober** [comment]
#115 will indeed address this, but currently waiting on some related work to fix history combination in pyuvdata.
