### ISSUE TITLE
Better specifications for selecting catalog sources

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyradiosky#42]
Should go in SkyModel object

specify more that just flux cuts -- there are markers for unreliable sources (probably sidelobe?), multiple components or gaussian parameters. Should be able to select only the point sources or just reliable ones.

Needs to be documented in the object so that it can be completely reproduced.

**Comment by jpober** [comment]
This is a pretty broad issue overall.  We're going to close, but users should open new issues to request support for specific use cases.
