### ISSUE TITLE
Band edges vs. centers

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/pyradiosky#50]
Do we want to support definitions of subband models by band edges instead of by band centers?

**Comment by bhazelton** [comment]
Definitely. I think we actually need both, so that the freq_array has length Nfreqs and then we have another array with length Nfreqs + 1

**Comment by bhazelton** [comment]
Thinking on this more, I think we want 2 new arrays of length Nfreqs, one for the band bottom and one for the band top. Doing it that way allows the subbands to be spaced out rather than requiring that they are all adjacent which using a single band_edges array would require.

**Comment by jpober** [comment]
Could potentially done with a (2, Nbands) array rather than two arrays.

**Comment by bhazelton** [comment]
We are implementing this and ran into a question. Our initial implementation was to require the new `freq_edge_array` for both `subband` and `full` spectral type objects.

When we started thinking about how to handle that array in the `at_frequencies` method we got confused. As a reminder: the `at_frequencies` method returns a new `full` type spectral object which is constructed by selecting, interpolating or evaluating (for full, subband and spectral index type objects respectively) along the frequency axis. It's unclear to us what to set the `freq_edge_array` to after this process (particularly for interpolation or evaluation).

I recall that one of the primary purposes for the `full` type was to support EoR maps which cannot be sensibly interpolated along the frequency axis.

We are wondering if maybe the `freq_edge_array` should only be required for `subband` objects, not `full` objects (although it could be set for those if desired). Thoughts? @jpober

**Comment by jpober** [comment]
The idea becomes that `full` is basically meant for contiguous, evenly spaced channels?  It's true that subbands are the most likely place to get non-symmetric, non-evenly spaced bands.  So I'm fine with this and seeing if anyone ever comes up with a use case that drives us to provide this kind of information for a `full` object.
