### ISSUE TITLE
How to combine catalogs with different spectral structure

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/pyradiosky#51]
Discussed in telecon on 3/23/20.

Some options:
1. Define a freq array for the whole catalog with nans for non-defined freqs?
    - Weird having NaNs everywhere.
    - Similar memory overhead.

2. Require that you interpolate every source to every frequency to be used.
    - Funky things happen depending on your choice of interpolation method.
    - A lot of memory overhead.

3. Nested skymodel objects?
    - Difficult to implement.
    - Maybe unclear to the user what's happening.

**Comment by bhazelton** [comment]
On the June 1, 2020 telecon we decided that we will not combine catalogs with different `spectral_type` or different `freq_array`. Users can call the new `at_frequencies` method to make all catalogs `full` type at a list of frequencies and then they can be combined.
