### ISSUE TITLE
Use astropy quantities

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyradiosky#8]
A lot of things are not astropy quantities, largely driven by a need for computational efficiency in pyuvsim.  We could have pyradiosky use quantities and make it pyuvsim's job to convert to floats where efficient.

**Comment by jpober** [comment]
Need to be careful we don't increase run time, but in some ways it's not pyradiosky's job to be fast, as long as a method exists to create numpy or other fast representations of the catalog for pyuvsim.

**Comment by bhazelton** [comment]
PR 49 takes care of some of them but not flux yet.
