### ISSUE TITLE
Make `from_xxx` classmethod

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyradiosky#87]
https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/485c122592087eca695ae4285af13584a391f375/pyradiosky/skymodel.py#L1568

Is there a good reason the `from_xxx` methods aren't class methods, so one could do `sky_model = SkyModel.from_recarray(path)`?

**Comment by bhazelton** [comment]
Not really, I think we just didn't think about it. Feel free to make a PR!
