### ISSUE TITLE
better handling for lists of quantities in __init__

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyradiosky#99]
Currently, if any of the parameters are supplied as lists of astropy quantities, they are converted to a numpy array (via `atleast_1d`) which strips the unit information. Then it errors with an unhelpful error message: `TypeError: only dimensionless scalar quantities can be converted to Python scalars`.

At a minimum we should provide a better error message. Even better would be to properly turn the list into a quantity array.

**Comment by mkolopanis** [comment]
We may also investigate calling `astropy.units.Quantity` on the input before the `np.atleast_1d` call. If this works the way I expect/remember, it should turn a list of quantities into a quantity of an array as well as do equivalency checking. We should test this obviously.
